[[redirects]]
  from = "/api"
  to = "https://cdpdev.intra.aicreate360.com/api"
  status = 200

[[redirects]]
    from = "/:tid/api"
    to = "https://cdpdev.intra.aicreate360.com/:tid/api"
    status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200